### ISSUE TITLE
Empty arguments aren't handled properly

### ISSUE THREAD

**Issue by blyxxyz** [faissaloo/echo#2]
Giving arguments with a length of 0 sometimes causes other arguments not to be printed.

```
$ ./echo X
X
$ ./echo "" X

$ ./echo "" XX

$ ./echo "" XXX
 XXX
```

**Comment by faissaloo** [comment]
The issue seems to happen when ecx is either 0x80000080 or 0x00800080 in _strlen. I'll try just doing a test ecx, 0x80 before all other comparisons tomorrow
Edit: It seems all I have to do is just start from 0x80 instead of 0x80000000

**Comment by faissaloo** [comment]
Fixed in https://github.com/faissaloo/echo/commit/2e9032b066f61c0ca32b768dd09ae911b39d811a , closing
