### ISSUE TITLE
Can't build on macOS

### ISSUE THREAD

**Issue by ghost** [faissaloo/echo#4]
I tried building echo.asm on macOS and got this.

```
echo-master $ ./build.sh
echo.asm:37: error: expression syntax error
echo.asm:51: error: expression syntax error
...
```

I looked at the source, but I was clueless.

**Comment by faissaloo** [comment]
Can you please post the result of:  

```
nasm -v
```

It seems to be having trouble with the backticks.  
Just a side note the program won't work on OSX because the syscalls will have a different syntax and usage and OSX can't run ELF binaries.

**Comment by ghost** [comment]
```
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Feb 10 2016
```

Ah, I see. I should've known better 😓

**Comment by faissaloo** [comment]
Yeah that's the issue there, your version of NASM is extremely old, you'll want to be using at least version 2 I think which you can get with homebrew or macports.
